# DigitalOcean App Platform Specification
# Deploy with: doctl apps create --spec .do/app.yaml

name: strapi-next-starter
region: nyc

# Managed Database
databases:
  - name: strapi-db
    engine: PG
    version: "16"
    size: db-s-dev-database  # $7/month
    num_nodes: 1

# Strapi Backend Service
services:
  - name: strapi
    source_dir: /server
    github:
      repo: your-username/your-repo  # Update this!
      branch: main
      deploy_on_push: true
    dockerfile_path: server/Dockerfile
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb  # $12/month
    http_port: 1337
    health_check:
      http_path: /_health
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_HOST
        value: ${strapi-db.HOSTNAME}
      - key: DATABASE_PORT
        value: ${strapi-db.PORT}
      - key: DATABASE_NAME
        value: ${strapi-db.DATABASE}
      - key: DATABASE_USERNAME
        value: ${strapi-db.USERNAME}
      - key: DATABASE_PASSWORD
        value: ${strapi-db.PASSWORD}
      - key: DATABASE_SSL
        value: "true"
      - key: JWT_SECRET
        type: SECRET
        value: "CHANGE_ME"
      - key: ADMIN_JWT_SECRET
        type: SECRET
        value: "CHANGE_ME"
      - key: APP_KEYS
        type: SECRET
        value: "key1,key2,key3,key4"
      - key: API_TOKEN_SALT
        type: SECRET
        value: "CHANGE_ME"
      - key: TRANSFER_TOKEN_SALT
        type: SECRET
        value: "CHANGE_ME"

  # Next.js Frontend Service
  - name: nextjs
    source_dir: /client
    github:
      repo: your-username/your-repo  # Update this!
      branch: main
      deploy_on_push: true
    dockerfile_path: client/Dockerfile
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb  # $6/month
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: STRAPI_BASE_URL
        value: ${strapi.PRIVATE_URL}
      - key: NEXT_PUBLIC_STRAPI_URL
        value: ${strapi.PUBLIC_URL}

# Ingress Rules (routing)
ingress:
  rules:
    - component:
        name: strapi
      match:
        path:
          prefix: /admin
    - component:
        name: strapi
      match:
        path:
          prefix: /api
    - component:
        name: strapi
      match:
        path:
          prefix: /uploads
    - component:
        name: nextjs
      match:
        path:
          prefix: /
